---

# https://github.com/wayofdev/gh-actions/blob/master/.github/workflows/create-release.yml
# https://github.com/google-github-actions/release-please-action#release-types-supported

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

name: 📦 Create release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 🎉 Create release
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/.release-please-config.json
          manifest-file: .github/.release-please-manifest.json
          target-branch: 2.x

...
